// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:boolean):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;
