// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(
  arg1: string,
  arg2: boolean,
  arg3: string,
): Promise<void>;

export function Disconnect(): Promise<void>;

export function SendTextMessage(arg1: string): Promise<void>;
